name: newserverdemo
description: A new Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  at_client_mobile: ^1.0.0+4
  at_server_status: ^0.1.0+1
  cupertino_icons: ^0.1.3
  modal_progress_hud: any
  at_demo_data: ^0.0.3+1
  at_chat_flutter: ^0.0.3
  atsign_authentication_helper: ^0.0.2

flutter:
  assets:
    - assets/mahi.png
  uses-material-design: true